import React from "react"
import Head from "next/head"

export const metadata = {
  title: "NetMapper",
  description: "Generated by Next.js",
}

export default function RootLayout({ children }) {
  return (
    <>
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <div>{children}</div>
    </>
  )
}
